import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  // next-env.d.ts and .next are generated by the framework, so linting them only ever
  // reports style the project does not control.
  // Build output, not source: .netlify and .vercel appear once a deploy has been run locally
  // and hold bundled copies of the app that would otherwise be linted.
  { ignores: [".next/**", ".netlify/**", ".vercel/**", "out/**", "node_modules/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
